export const SITE = {
  name: "Istiak Ahmad",
  url: "https://istiakahmad.com",
  title: "Istiak Ahmad | Product Hunt Launch Expert",
  description:
    "I help founders rank Top #1 on Product Hunt. SaaS founder, verified hunter, and launch strategist with 8+ top-ranked launches.",
  links: {
    gumroad: "https://istiakahmad.gumroad.com/l/PH-launch-success-playbook",
    upwork: "https://www.upwork.com/freelancers/~01f5ac9cdcaaad7afb",
    consultation:
      "https://www.upwork.com/services/product/marketing-istiak-1967903406702102605?ref=project_share",
    producthunt: "https://www.producthunt.com/@istiakahmad",
    linkedin: "https://www.linkedin.com/in/istiak-ahmad/",
    
    youtube: "https://www.youtube.com/@istiakahmadyoutube",
    whatsapp: "https://wa.me/447480676782",
    whatsappChannel: "https://whatsapp.com/channel/0029VbB5eyAGOj9gQgSQGC1F",
    tidycal: "https://tidycal.com/istiakahmad/consultation",
    ebookVideo: "https://www.youtube.com/embed/8U_mE4SaiHI",
    lancepilot: "https://www.producthunt.com/products/lancepilot/launches/lancepilot",
  },
} as const;

export const LAUNCHES = [
  {
    name: "Lancepilot",
    role: "Founder & Maker",
    date: "April 8, 2024",
    rank: "#1 Product of the Day",
    extra: ["#2 Week", "#1 Marketing / Week", "#1 Marketing / Month"],
    description:
      "WhatsApp marketing software for campaigns, tracking, scheduling & CRM. My own SaaS, launched to the top of Product Hunt.",
    href: "https://www.producthunt.com/products/lancepilot/launches/lancepilot",
    featured: true,
  },
  {
    name: "AutoEdit",
    role: "Hunter",
    date: "June 15, 2026",
    rank: "#3 Product of the Day",
    extra: [],
    description: "Claude AI video editor for Premiere Pro. Hunted to a Top 3 finish on launch day.",
    href: "https://www.producthunt.com/products/autoedit",
  },
  {
    name: "Revolte",
    role: "Hunter",
    date: "May 28, 2026",
    rank: "#4 Product of the Day",
    extra: [],
    description: "AI for software engineering. Hunted to a Top 5 finish on launch day.",
    href: "https://www.producthunt.com/products/revolte",
  },
  {
    name: "Nomie",
    role: "Hunter",
    date: "March 23, 2026",
    rank: "#5 Product of the Day",
    extra: [],
    description: "Hunted and managed launch to a featured Top 5 finish.",
    href: "https://www.producthunt.com/products/nomie",
  },
  {
    name: "Simply",
    role: "Hunter",
    date: "March 9, 2026",
    rank: "#4 Product of the Day",
    extra: [],
    description: "End-to-end launch management, secured a Top 5 finish.",
    href: "https://www.producthunt.com/products/simply-4",
  },
  {
    name: "ToolSpend",
    role: "Hunter",
    date: "February 16, 2026",
    rank: "#2 Product of the Day",
    extra: [],
    description: "Outreach + launch-day execution to a runner-up finish.",
    href: "https://www.producthunt.com/products/toolspend",
  },
  {
    name: "Jector AI",
    role: "Hunter",
    date: "May 27, 2024",
    rank: "#3 Product of the Day",
    extra: [],
    description: "Hunted AI image generator to a podium finish on launch day.",
    href: "https://www.producthunt.com/products/jector-ai-2/launches/jector-ai",
  },
  {
    name: "Ginix",
    role: "Hunter",
    date: "June 2, 2024",
    rank: "#1 Product of the Day",
    extra: [],
    description: "Review monitoring platform. Hunted to #1 of the day.",
    href: "https://www.producthunt.com/products/free-platform-for-monitoring-reviews/launches/ginix",
  },
] as const;
