/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as IaLoginRouteImport } from './routes/ia-login'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminTrackingRouteImport } from './routes/admin.tracking'
import { Route as AdminSiteSettingsRouteImport } from './routes/admin.site-settings'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLaunchesRouteImport } from './routes/admin.launches'
import { Route as AdminDealsRouteImport } from './routes/admin.deals'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAccountRouteImport } from './routes/admin.account'
import { Route as AdminPagesKeyRouteImport } from './routes/admin.pages.$key'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IaLoginRoute = IaLoginRouteImport.update({
  id: '/ia-login',
  path: '/ia-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminTrackingRoute = AdminTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaunchesRoute = AdminLaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesKeyRoute = AdminPagesKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => AdminPagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/ia-login': typeof IaLoginRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/playbook': typeof PlaybookRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/launches': typeof AdminLaunchesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pages/$key': typeof AdminPagesKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/ia-login': typeof IaLoginRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/playbook': typeof PlaybookRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/launches': typeof AdminLaunchesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pages/$key': typeof AdminPagesKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/ia-login': typeof IaLoginRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/playbook': typeof PlaybookRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/launches': typeof AdminLaunchesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pages/$key': typeof AdminPagesKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/deals'
    | '/ia-login'
    | '/llms.txt'
    | '/playbook'
    | '/portfolio'
    | '/privacy'
    | '/products'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/account'
    | '/admin/audit'
    | '/admin/deals'
    | '/admin/launches'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/seo'
    | '/admin/site-settings'
    | '/admin/tracking'
    | '/products/$slug'
    | '/admin/'
    | '/admin/pages/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/deals'
    | '/ia-login'
    | '/llms.txt'
    | '/playbook'
    | '/portfolio'
    | '/privacy'
    | '/products'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/account'
    | '/admin/audit'
    | '/admin/deals'
    | '/admin/launches'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/seo'
    | '/admin/site-settings'
    | '/admin/tracking'
    | '/products/$slug'
    | '/admin'
    | '/admin/pages/$key'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/deals'
    | '/ia-login'
    | '/llms.txt'
    | '/playbook'
    | '/portfolio'
    | '/privacy'
    | '/products'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/account'
    | '/admin/audit'
    | '/admin/deals'
    | '/admin/launches'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/seo'
    | '/admin/site-settings'
    | '/admin/tracking'
    | '/products/$slug'
    | '/admin/'
    | '/admin/pages/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRoute
  IaLoginRoute: typeof IaLoginRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PlaybookRoute: typeof PlaybookRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-login': {
      id: '/ia-login'
      path: '/ia-login'
      fullPath: '/ia-login'
      preLoaderRoute: typeof IaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/tracking': {
      id: '/admin/tracking'
      path: '/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AdminTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-settings': {
      id: '/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/launches': {
      id: '/admin/launches'
      path: '/launches'
      fullPath: '/admin/launches'
      preLoaderRoute: typeof AdminLaunchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/$key': {
      id: '/admin/pages/$key'
      path: '/$key'
      fullPath: '/admin/pages/$key'
      preLoaderRoute: typeof AdminPagesKeyRouteImport
      parentRoute: typeof AdminPagesRoute
    }
  }
}

interface AdminPagesRouteChildren {
  AdminPagesKeyRoute: typeof AdminPagesKeyRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesKeyRoute: AdminPagesKeyRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminLaunchesRoute: typeof AdminLaunchesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminTrackingRoute: typeof AdminTrackingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminLaunchesRoute: AdminLaunchesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminProductsRoute: AdminProductsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminTrackingRoute: AdminTrackingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRoute,
  IaLoginRoute: IaLoginRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PlaybookRoute: PlaybookRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
